name: Close GitHub Issues from Jira

on:
  repository_dispatch:
    types: [jira-release]

permissions:
  issues: write

jobs:
  close:
    runs-on: ubuntu-latest

    steps:
      - name: Dump payload
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context.payload, null, 2));
      - name: Close issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload.client_payload;

            const version = payload.version;
            const issues = payload.issues;

            console.log(`Version ${version} released.`);
            console.log(issues);

            for (const number of issues) {

              console.log(`Closing issue #${number}`);

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                body: `✅ Fixed in **${version}**.`
              });

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                state: "closed"
              });
            }
